- name: Plex Postreq - Ensure Plex SSL script and resources
  when: hms_docker_plex_ssl_enabled and traefik_ssl_enabled and custom_scripts_enabled
  block:
    - name: Plex Postreq - Plex SSL - Ensure pkcs12 script
      ansible.builtin.copy:
        src: scripts/traefik_cert_convert.py
        dest: "{{ hms_docker_data_path }}"
        mode: '700'
        owner: "{{ container_uid }}"
        group: "{{ container_gid }}"
      register: cert_script

    - name: Plex Postreq - Plex SSL - Ensure cron job
      ansible.builtin.cron:
        name: "{{ project_name }}-plex-ssl"
        user: root
        job: "{{ hms_docker_data_path }}/.venv/bin/python {{ cert_script.dest | default(hms_docker_data_path + '/traefik_cert_convert.py') }}"
        minute: 0
        hour: 5
