
  - name: Traefik Postreq - Verify all Traefik endpoints are accessible
    ansible.builtin.uri:
      url: http://{{ item }}.{{ hms_docker_domain }}
      status_code: 200,302,401,403
      validate_certs: false
    loop: "{{ traefik_enabled_subdomains }}"
    when:
      - "'traefik' in enabled_containers"
      - traefik_verify_endpoints | default(false)
    ignore_errors: true
    register: traefik_successful_endpoints
