  - name: Traefik Postreq - Extend Traefik check list if 4K instances are enabled
    ansible.builtin.set_fact:
      traefik_enabled_subdomains: "{{ traefik_enabled_subdomains + [item + '-4k'] }}"
    when:
      - separate_4k_instances_enable
      - item in enabled_containers
    loop:
      - sonarr
      - radarr

  - name: Traefik Postreq - Verify all Traefik endpoints are accessible
    ansible.builtin.uri:
      url: http://{{ item }}.{{ hms_docker_domain }}
      status_code: 200,302,401,403
      validate_certs: false
    loop: "{{ traefik_enabled_subdomains }}"
    when:
      - hmsdocker_container_enabled_traefik
      - traefik_verify_endpoints | default(false)
    ignore_errors: true
    register: traefik_successful_endpoints
