---
- hosts: all
  become: yes
  gather_facts: yes
  vars:
    hmsd_current_version: 1.8
    hmsd_version_file: "{{ hms_docker_data_path }}/.hmsd-version"
    regex: '[^A-Za-z0-9._-]'
    replace: '_'
    arr_apikey: '(?<=\<ApiKey\>)\w*(?=\<\/ApiKey\>)'
    debug_mode: false

  roles:
    - galaxy-roles/geerlingguy.docker

  tasks:
  - name: Ensure Nvidia GPU role if enabled
    ansible.builtin.import_role:
      name: gpu
    when: enable_nvidia_gpu is defined and enable_nvidia_gpu

  - name: Ensure HMS-Docker role
    ansible.builtin.import_role:
      name: hmsdocker
