#######################################################################
# Computed variables
#######################################################################
### Misc
hmsdocker_primary_mount_path: "{{ hms_docker_mount_path }}/{{ hms_docker_primary_mount_name }}"
# This just combines the mount path and media folder name, recommended to leave this alone // default: "{{ hmsdocker_primary_mount_path }}/{{ hms_docker_library_folder_name }}"
hmsdocker_library_path: "{{ hmsdocker_primary_mount_path }}/{{ hms_docker_library_folder_name }}"
#######################################################################


#######################################################################
### Advanced Ansible settings
# Overrides the family to 'redhat' if running Alma Linux
hmsdocker_family_override: "{{ 'redhat' if ansible_os_family | lower == 'almalinux' else ansible_os_family | lower }}"

# Which python interpreter to use, only change if you're an advanced user and know what you're doing
ansible_python_interpreter: /usr/bin/python3
#######################################################################
