---
- name: Arr Scripts - Check for App Config Dirs
  ansible.builtin.stat:
    path: "{{ hms_docker_apps_path }}/{{ item }}"
  loop:
    - radarr
    - sonarr
    - radarr-4k
    - sonarr-4k
    - lidarr
    - sabnzbd
  register: arr_script_app_config_dirs

- name: Arr Scripts - Download Init Script
  when:
    - item in enabled_containers
    - arr_script_app_config_dirs.results | selectattr('item', 'equalto', item) | selectattr('stat.exists', 'equalto', true) | list | length > 0
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/RandomNinjaAtk/arr-scripts/main/{{ item }}/scripts_init.bash
    dest: "{{ hms_docker_apps_path }}/{{ item }}/custom-cont-init.d"
    owner: "{{ container_uid }}"
    group: "{{ container_gid }}"
    mode: "0755"
  notify: Restart {{ item }}
  loop:
    - radarr
    - sonarr
    - lidarr
    - sabnzbd

- name: Arr Scripts - 4K Instances - Download Init Script
  when:
    - item in enabled_containers
    - separate_4k_instances_enable | default(false)
    - arr_script_app_config_dirs.results | selectattr('item', 'equalto', item) | selectattr('stat.exists', 'equalto', true) | list | length > 0
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/RandomNinjaAtk/arr-scripts/main/{{ item }}/scripts_init.bash
    dest: "{{ hms_docker_apps_path }}/{{ item }}-4k/custom-cont-init.d"
    owner: "{{ container_uid }}"
    group: "{{ container_gid }}"
    mode: "0755"
  notify: Restart {{ item }} 4K
  loop:
    - radarr
    - sonarr
