---
- name: Custom Scripts - Ensure venv pip package
  ansible.builtin.package:
    name:
      - python3-venv
    state: present

- name: Custom Scripts - Ensure pip is updated first
  ansible.builtin.pip:
    virtualenv: "{{ hms_docker_data_path }}/.venv"
    virtualenv_command: "{{ ansible_python_interpreter }} -m venv"
    name:
      - pip
    state: latest

- name: Custom Scripts - Ensure pip environment
  ansible.builtin.pip:
    virtualenv: "{{ hms_docker_data_path }}/.venv"
    virtualenv_site_packages: true
    name:
      - requests
      - python-dotenv
      - xmltodict
      - cryptography
      - docker
      - defusedxml

- name: Custom Scripts - Ensure scripts folder
  ansible.builtin.file:
    path: "{{ hms_docker_data_path }}/scripts"
    state: directory
    owner: root
    group: root
    mode: 0755
  register: scripts_path

- name: Custom Scripts - Ensure env symlink
  ansible.builtin.file:
    state: link
    src: "{{ compose_env.dest | default(hms_docker_data_path + '/.env') }}"
    dest: "{{ scripts_path.path }}/.env"
    force: "{{ ansible_check_mode }}"

- name: Custom Scripts - Plex SSL - Ensure Plex SSL script and resources
  when: hms_docker_plex_ssl_enabled and traefik_ssl_enabled
  block:
    - name: Custom Scripts - Plex SSL - Ensure pkcs12 script
      ansible.builtin.copy:
        src: scripts/traefik_cert_convert.py
        dest: "{{ scripts_path.path }}"
        mode: '700'
        owner: "{{ container_uid }}"
        group: "{{ container_gid }}"
      register: cert_script

    - name: Custom Scripts - Plex SSL - Ensure cron job
      ansible.builtin.cron:
        name: "{{ project_name }}-plex-ssl"
        user: root
        job: "{{ hms_docker_data_path }}/.venv/bin/python {{ cert_script.dest | default(hms_docker_data_path + '/scripts/traefik_cert_convert.py') }}"
        minute: 0
        hour: 5

- name: Custom Scripts - Ensure monitoring scripts
  when: monitoring_scripts_enabled | default(false)
  block:
    - name: Custom Scripts - Ensure monitoring directory
      ansible.builtin.file:
        path: "{{ scripts_path.path }}/monitoring"
        state: directory
        owner: root
        group: root
        mode: 0755
      register: monitoring_scripts_path

    - name: Custom Scripts - Ensure env symlink
      ansible.builtin.file:
        state: link
        src: "{{ compose_env.dest | default(hms_docker_data_path + '/.env') }}"
        dest: "{{ monitoring_scripts_path.path }}/.env"
        force: "{{ ansible_check_mode }}"

    - name: Custom Scripts - Ensure monitoring scripts
      ansible.builtin.copy:
        src: scripts/monitoring
        dest: "{{ scripts_path.path }}"
        mode: 0700

    - name: Custom Scripts - Ensure media availability cron
      ansible.builtin.cron:
        name: "{{ project_name }}-media-availability-monitoring"
        user: root
        job: "{{ hms_docker_data_path }}/.venv/bin/python3 {{ monitoring_scripts_path.path }}/check_media_availability.py"
        minute: "*"
