- name: Readarr bootstrap - Init Readarr
  block:
    - name: Readarr bootstrap - Ensure Readarr Config
      block:
        - name: Readarr bootstrap - Get readarr container info
          community.docker.docker_container_info:
            name: readarr
          register: readarr_container_info

        - name: Readarr bootstrap - Set Readarr facts
          ansible.builtin.set_fact:
            readarr_url: "http{{ 's' if traefik_ssl_enabled and not hmsdocker_expose_ports_enabled_readarr }}://{{ hms_docker_container_map['readarr']['proxy_host_rule'] }}.{{ hms_docker_domain }}{{ ':8787' if hmsdocker_expose_ports_enabled_readarr }}/api"

        - name: Readarr bootstrap - Precheck Readarr API Key
          ansible.builtin.uri:
            url: "{{ readarr_url }}"
            method: GET
            status_code: 200
            body_format: json
            return_content: true
            headers:
              X-Api-Key: "{{ slurped_api_key_readarr['content'] | b64decode | regex_search(arr_apikey) }}"
          register: readarr_api_key_precheck

        - name: Readarr bootstrap - Ensure download clients in Readarr
          block:
            - name: Readarr bootstrap - Get download clients
              ansible.builtin.uri:
                url: "{{ readarr_url }}/v1/downloadclient"
                method: GET
                status_code: 200
                body_format: json
                return_content: true
                headers:
                  X-Api-Key: "{{ slurped_api_key_readarr['content'] | b64decode | regex_search(arr_apikey) }}"
              register: readarr_downloaders

            - name: Readarr bootstrap - Set Readarr download client Facts
              ansible.builtin.set_fact:
                readarr_download_clients: "{{ readarr_downloaders.json | items2dict(key_name='name', value_name='id') }}" # | json_query('[].name') }}"

            - name: Readarr bootstrap - Configure Transmission download client in Readarr
              when:
                - hmsd_app_init_config_prefix + 'Transmission' not in readarr_download_clients.keys()
                - "'transmission' in enabled_containers"
              ansible.builtin.uri:
                url: "{{ readarr_url }}/v1/downloadclient"
                method: POST
                body: {
                  name: "{{ hmsd_app_init_config_prefix }}Transmission",
                  implementation: "Transmission",
                  configContract: "TransmissionSettings",
                  removeCompletedDownloads: true,
                  removeFailedDownloads: true,
                  priority: 1,
                  enable: true,
                  fields: [
                    {
                      name: "host",
                      value: "transmission"
                    },
                    {
                      name: "port",
                      value: 9091
                    },
                    {
                      name: "useSsl",
                      value: false
                    },
                    {
                      name: "urlBase",
                      value: "/transmission/"
                    },
                    {
                      name: "username"
                    },
                    {
                      name: "password"
                    },
                    {
                      name: "musicCategory",
                      value: "books-readarr"
                    },
                    {
                      name: "booksDirectory"
                    },
                    {
                      name: "recentTvPriority",
                      value: 0
                    },
                    {
                      name: "olderTvPriority",
                      value: 0
                    },
                    {
                      name: "addPaused",
                      value: false
                    }
                  ]
                }
                status_code: 201
                body_format: json
                return_content: true
                headers:
                  X-Api-Key: "{{ slurped_api_key_readarr['content'] | b64decode | regex_search(arr_apikey) }}"
              register: readarr_req_add_download_client
              changed_when: readarr_req_add_download_client.status == 201

            - name: Readarr bootstrap - Configure qBittorrent download client in Readarr
              when:
                - hmsd_app_init_config_prefix + 'qBittorrent' not in readarr_download_clients.keys()
                - "'qbittorrent' in enabled_containers"
              ansible.builtin.uri:
                url: "{{ readarr_url }}/v1/downloadclient"
                method: POST
                body: {
                  name: "{{ hmsd_app_init_config_prefix }}qBittorrent",
                  enable: true,
                  priority: 1,
                  implementation: "QBittorrent",
                  configContract: "QBittorrentSettings",
                  removeCompletedDownloads: true,
                  removeFailedDownloads: true,
                  fields: [
                    {
                      name: "host",
                      value: "qbittorrent"
                    },
                    {
                      name: "port",
                      value: 8086
                    },
                    {
                      name: "useSsl",
                      value: false
                    },
                    {
                      name: "urlBase"
                    },
                    {
                      name: "username"
                    },
                    {
                      name: "password"
                    },
                    {
                      name: "musicCategory",
                      value: "books-readarr"
                    },
                    {
                      name: "recentTvPriority",
                      value: 0
                    },
                    {
                      name: "olderTvPriority",
                      value: 0
                    },
                    {
                      name: "initialState",
                      value: 0
                    },
                    {
                      name: "sequentialOrder",
                      value: false
                    },
                    {
                      name: "firstAndLast",
                      value: false
                    },
                    {
                      name: "contentLayout",
                      value: 0
                    }
                  ],
                }
                status_code: 201
                body_format: json
                return_content: true
                headers:
                  X-Api-Key: "{{ slurped_api_key_readarr['content'] | b64decode | regex_search(arr_apikey) }}"
              register: readarr_req_add_download_client
              changed_when: readarr_req_add_download_client.status == 201

            - name: Readarr bootstrap - Configure Deluge download client in Readarr
              when:
                - hmsd_app_init_config_prefix + 'Deluge' not in readarr_download_clients.keys()
                - "'deluge' in enabled_containers"
              ansible.builtin.uri:
                url: "{{ readarr_url }}/v1/downloadclient"
                method: POST
                body: {
                  name: "{{ hmsd_app_init_config_prefix }}Deluge",
                  enable: true,
                  priority: 1,
                  implementation: "Deluge",
                  configContract: "DelugeSettings",
                  removeCompletedDownloads: true,
                  removeFailedDownloads: true,
                  fields: [
                    {
                      name: "host",
                      value: "deluge"
                    },
                    {
                      name: "port",
                      value: 8112
                    },
                    {
                      name: "useSsl",
                      value: false
                    },
                    {
                      name: "urlBase"
                    },
                    {
                      name: "username"
                    },
                    {
                      name: "password",
                      value: "deluge"
                    },
                    {
                      name: "musicCategory",
                      value: ""
                    },
                    {
                      name: "recentTvPriority",
                      value: 0
                    },
                    {
                      name: "olderTvPriority",
                      value: 0
                    },
                    {
                      name: "initialState",
                      value: 0
                    },
                    {
                      name: "sequentialOrder",
                      value: false
                    },
                    {
                      name: "firstAndLast",
                      value: false
                    },
                    {
                      name: "contentLayout",
                      value: 0
                    }
                  ],
                }
                status_code: 201
                body_format: json
                return_content: true
                headers:
                  X-Api-Key: "{{ slurped_api_key_readarr['content'] | b64decode | regex_search(arr_apikey) }}"
              register: readarr_req_add_download_client
              changed_when: readarr_req_add_download_client.status == 201

            - name: Readarr bootstrap - Remove download clients in Readarr if not enabled
              when:
                - hmsd_app_init_config_prefix + item in readarr_download_clients.keys()
                - item | lower not in enabled_containers
                - hmsdocker_app_bootstrap_delete_unused
              ansible.builtin.uri:
                url: "{{ readarr_url }}/v1/downloadclient/{{ readarr_download_clients[hmsd_app_init_config_prefix + item] }}"
                method: DELETE
                status_code: 200
                headers:
                  X-Api-Key: "{{ slurped_api_key_readarr['content'] | b64decode | regex_search(arr_apikey) }}"
              register: readarr_req_del_download_client
              changed_when: readarr_req_del_download_client.status == 200
              loop:
                - Transmission
                - qBittorrent
                - Deluge
