---
- name: NAS - NFS - Ensure RedHat NFS packages.
  ansible.builtin.package:
    name:
      - nfs-utils
    state: "{{ nas_client_package_state }}"
  when: hmsdocker_family_override | lower == "redhat"

- name: NAS - NFS - Ensure Debian NFS packages.
  ansible.builtin.package:
    name:
      - nfs-common
    state: "{{ nas_client_package_state }}"
  when: ansible_facts['os_family'] | lower == "debian"

- name: NAS - NFS - Ensure NFS fstab entry and mount.
  ansible.posix.mount:
    backup: yes
    boot: "{{ nas_client_mount_on_boot }}"
    path: "{{ hmsdocker_primary_mount_path }}"
    src: "{{ nas_client_remote_nfs_path }}"
    fstype: nfs
    opts: "{{ nas_client_nfs_opts }}"
    state: "{{ nas_client_mount_state }}"
